import React from "react"

function ProContro(){
    return(
        <div className="try_Text">
            <h1>Pro - Oro</h1>
            <h2>L’importanza della decentralizzazione</h2>
            <h3>Una moneta libera - Pro</h3>
            <p>Blockchain, come si può leggere all’inizio del whitepaper di Bitcoin di Nakamoto, nasce con un obiettivo ben preciso: un sistema per inviare denaro online tra utenti senza la presenza di un garante finanziario esterno. Se per lo scambio di moneta legale online è necessaria la presenza di un ente finanziario, di un circuito bancario ad esempio, che verifichi la validità delle transazioni, lo stesso non si può dire per una cryptovaluta legata ad una blockchain. In questo caso, come abbiamo visto in precedenza, il consenso è distribuito, ed è la rete stessa a fungere da garante per le transazioni al suo interno, operando come un sistema trustless in cui tutti si fidano di tutti e nessuno si fida di nessuno. 
            Ma quali sono I vantaggi di avere una moneta decentralizzata?
            Le cryptovalute che si appoggiano a blockchain non sono controllate da governi o banche centrali. Il loro valore non può essere modificato arbitrariamente da un singolo ente al di sopra del sistema, come ad esempio uno stato che può svalutare la moneta stampandola in quantità esagerate e aumentando così l’inflazione in maniera artificiale, ma è autoregolato dal mercato interno. Le cryptovalute inoltre, non essendo sotto il controllo diretto di nessuno al di fuori dell’utente che le possiede, non possono essere confiscate. Quando ci si appoggia a blockchain non esiste un’unica banca, l’utente può essere la propria banca.
            Il fatto che non ci sia un ente terzo a controllare le transazioni implica inoltre che non ci sia un rischio di censura sulle transazioni stesse. Le cryptovalute legate a blockchain sono permission-less, non richiedono alcun permesso da parte di enti esterni per essere spese al di fuori del consenso della rete, dal momento che i conti degli utenti sono in chiaro nello storico della blockchain l’unico vincolo per la validità di una transazione è che l’utente che invia il denaro possegga effettivamente la cifra che vuole spendere. In un sistema così non esiste censura, e ognuno è libero di inviare denaro in qualsiasi parte del mondo, a chiunque voglia. 
            Il fatto che tutte le operazioni siano in chiaro rende le frodi quasi impossibili, il consenso è distribuito e l’unico modo per eludere il controllo della rete è avere più potere decisionale della rete stessa. La decentralizzazione della rete rende inoltre le transazioni più efficienti, si paga una quota ridotta ai miner per inserire la transazione in un blocco ma è di gran lunga minore rispetto alle tasse imposte dai circuiti bancari, e più rapide, le transazioni infatti vengono convalidate nel giro di pochi minuti, non giorni o ore.
            I vantaggi di una moneta basata su blockchain sono insomma molti, e sono proprio I vantaggi concessi da questa tecnologia a dare un valore alle monete che la usano. Blockchain però non è un semplice apparato logistico a sostegno di una valuta, è un meccanismo per la gestione di un consenso distribuito che può avere altre applicazioni al di fuori di un contesto finanziario o monetario.
            </p>
            <h2>Oltre la moneta - Pro</h2>
            <p>Blockchain è una tecnologia molto versatile che può essere adottata in qualsiasi contesto che richieda un apparato di controllo trasparente, immutabile e sicuro. Per queste ragioni, blockchain si presta  molto bene per il controllo distribuito di dati di vario genere: laddove servano dei dati di qualsiasi tipo blockchain, grazie al consenso distribuito, può essere usata per garantire l’integrità e la validità di quei dati. Gli scenari d’uso possibili sono potenzialmente infiniti, molti ancora inesplorati, ma già oggi sono moltissime le applicazioni blockchain di matrice non strettamente monetaria o finanziaria. </p>
            <h3>Uso Governativo</h3>
            <p>All’apparenza può sembrare un paradosso, una tecnologia che nasce per sottrarre una moneta al potere di banche e governi come può essere utilizzata a scopo governativo? In realtà ci sono molti casi in cui il sistema di consenso offerto da blockchain può rivelarsi estremamente utile per un governo: dal controllo delle votazioni, passando alla gestione dei dati pubblici, per non parlare della gestione di documenti e quant’altro. Questi sono tutti scenari d’uso che richiedono un sistema trasparente, sicuro, e che garantisca l’integrità dei dati trattati, e blockchain, con la sua struttura decentralizzata, può essere un’ottima risposta a queste esigenze. 
            Esempi reali di nazioni che intendono usare blockchain a scopo governativo sono l’Olanda e la Finlandia. L'olanda ha intenzione di utilizzare blockchain per controllare i flussi ai confini statali, principalmente per la gestione dei permessi d’ingresso nei viaggi tra Amsterdam e Londra, mentre la finlandia sta sviluppando un sistema basato su blockchain per aiutare I centri di assunzione nelle aree rurali a gestire I dati degli iscritti.
            </p>
            <h3>Identità digitale</h3>
            <p>Anche se l’avvento del GDPR ha aiutato a ridurre il problema in europa, gran parte dei dati degli utenti in rete sono in mano a servizi e applicazioni che li richiedono per garantire il proprio funzionamento. Queste sono però entità completamente centralizzate, che non sempre operano in maniera trasparente, e che oltretutto non sono immuni ad attacchi informatici. I dati posseduti da questi siti sono un vero e proprio corpo d’informazioni che rappresentano un utente online; l'eventuale furto di questi dati è a tutti gli effetti un vero e proprio furto d’identità digitale. 
            Blockchain può aiutare a risolvere questo problema decentralizzando completamente I dati e  restituendo il controllo agli utenti. Invece di fornire automaticamente il consenso al trattamento dei dati, blockchain può essere usata per tenere traccia di chi è effettivamente autorizzato a poter accedere a quei dati.
            </p>
            <h3>Uso notarile</h3>
            <p>...</p>
            <h3>Sanità</h3>
            <p>....</p>
            <h1>Contro - Pirite</h1>
            <h2>Consumi Elettrici Rete BTC</h2>
            <h3>Intro</h3>
            <p>La necessità di risolvere un problema estremamente complesso da un punto di vista computazionale garantisce alla rete bitcoin una relativa sicurezza di fondo, si è visto infatti prima che per poter prendere il controllo della rete è necessario avere il controllo di più del 50% della potenza di calcolo globale della rete, ma il prezzo da pagare per questa forma di sicurezza è un elevato dispendio energetico. Per aumentare le possibilità di vincere un blocco ogni macchina presente nella rete utilizza infatti tutte le risorse energetiche a sua disposizione per generare più numeri casuali possibili al secondo. Ma quante macchine ci sono nella rete? E quanto consumano nello specifico? Non è possibile ottenere delle risposte precise a queste domande, non tutto l’hardware legato alla rete bitcoin è tracciabile (ad esempio, non è possibile avere delle stime sui consumi energetici dei sistemi di raffreddamento delle macchine nella rete), ma è possibile avere delle stime al ribasso abbastanza precise che ci danno un’idea di quanto siano i consumi minimi della rete.  </p>
            <h3>Numero minimo di Miner</h3>
            <p>È possibile definire con certezza un numero minimo di miner nella rete, e con esso anche il consumo complessivo da essi generato. Assumendo infatti che ogni miner nella rete sia un miner razionale, ovverosia un miner che mini in maniera legittima e con profitto, e che ogni miner utilizzi la propria macchina per più tempo possibile, è possibile vedere per ogni intervallo di tempo quale è la macchina che produce in quel momento il maggior numero di terahash possibili; se si divide poi I terahash complessivi della rete per I terahash della macchina più performante si ottiene il numero di miner, che andrà poi moltiplicato per il consumo della macchina. Questo calcolo ci dà una stima minima dei consumi sotto la quale non si può andare, ma è verosimile pensare che, per varie ragioni non tutti I miner nella rete utilizzino sempre la macchina più performante sul mercato (né che tutti I miner siano miner razionali). 
            È quindi proposta una stima che tiene conto anche dei costi di gestione e di altri fattori come affidabilità e profitto generato dalle macchine. I dati per questa stima, forniti da digiconomist, non prendono in considerazione i consumi dei sistemi di raffreddamento ma, tenendo conto dei guadagni generati dal mining, dalle stime sui costi della corrente, e da un indice che ipotizza che ogni miner spenda almeno il 60% dei propri guadagni in operazioni di manutenzione e gestione, ci danno un’idea più precisa di quali possano essere I veri consumi dell’intera rete bitcoin. 
            </p>
            <h3>Miner VS Industria</h3>
            <p>Per mettere a fuoco l’entità dei consumi della rete, è interessante confrontarla con quella delle produzioni industriali dei vari paesi del mondo. I risultati che la rete bitcoin consuma più della rete industriale [del paese X], ma, considerando che I consumi sono destinati a crescere, secondo le stime di Alex De Vries, fondatore di digiconomist, di almeno un altro 60%, è ipotizzabile che per il 2020 arrivi ai livelli del [paese Y].</p>
            <h3>Miner VS Casa</h3>
            <p>Ma quanto consuma una singola macchina per il mining nel dettaglio? Storicamente le prime macchine dedicate al mining erano dei semplici pc, si utilizzava infatti la potenza di calcolo offerta dai normali processori o dalle schede video dei PC di casa, di conseguenza il consumo dei primi miner era assimilabile a quello di un pc che lavorava a pieno carico per qualche ora. A partire dal 2013, però, con l’aumentare della complessità delle operazioni e del valore della moneta, si è iniziato a utilizzare hardware più specifico che utilizzasse nella maniera più efficiente possibile tutte le risorse a disposizione della macchina. Più efficienza però non vuol dire necessariamente consumi minori, anzi. Nel grafico proposto sotto si è deciso di mostrare la differenza di consumi tra un miner, un semplice computer che genera numeri casuali 24/7, e dei normali elettrodomestici presenti in ogni casa.</p>
            <h2>Inquinamento</h2>
            <h3>Bitcoin Inquinamento CO2</h3>
            <p>Un altro problema legato agli alti consumi derivati dalla proof-of-work sono le risorse utilizzate per soddisfare queste richieste energetiche. Considerando che la maggior parte della rete di miner è localizzata in asia, è lecito pensare che buona parte dell’energia elettrica utilizzata da questi miner venga prodotta attraverso l’utilizzo di carbone e altri combustibili fossili. Non essendo però possibile localizzare con esatta precisione la posizione dei miner nella rete, né sapere con esattezza quale tipo di energia stiano utilizzando, la metodologia adottata prevede un approccio che non tiene conto della geolocalizzazione dei miner. Si è deciso così di presentare una stima rapportando i consumi della rete bitcoin visti nella sezione precedente, minimi e stimati, con l’emissione media mondiale di kilotonnellate di CO2 per gigawattora di corrente. I dati per la conversione sono presi dall’IEA World Energy Outlook del 2017, e ci mostrano come in media, a livello mondiale, si producano 0.554Kg di CO2 per kWh.È interessante notare anche il confronto a livello mondiale tra le emissioni di CO2 della rete BTC e quelle delle produzioni industriali dei vari paesi. </p>
            <h2>Smaltimento</h2>
            <h3>Bitcoin RAEE</h3>
            <p>I problemi legati alla complessità dei calcoli necessaria per la validazione tramite proof-of-work non riguardano solo gli alti consumi energetici e la produzione di CO2 che da essi deriva, ma anche lo smaltimento dell’hardware usato per poter effettuare questi calcoli. 
            Per minare bitcoin nella maniera più efficiente possibile si utilizza un tipo di hardware estremamente specializzato, creato appositamente per risolvere problemi crittografici ben precisi, identificato con l’acronimo ASIC (application specific integrated circuit). Per quanto in passato fosse possibile minare con hardware utilizzabile anche per altri scopi, come CPU o GPU, o comunque hardware riconvertibile per minare anche altre criptovalute una volta diventato meno performante (FPGA), il drastico aumento della difficoltà dei blocchi, e di conseguenza l’aumento della richiesta di terahash necessari per vincere un blocco, ha spinto i produttori di hardware a creare delle macchine specializzate in un unico task, dette ASIC, che utilizzano tutte le risorse a loro disposizione solo ed esclusivamente per generare più terahash possibili in un task ben specifico. A differenza delle FPGA, gli ASIC non possono essere riconvertiti per minare criptovalute che utilizzino sistemi di crittografia differenti da quello per cui sono state creati. 
            Il continuo aumento della difficoltà per minare I blocchi, e quindi la richiesta di corrente necessaria per eseguire calcoli sempre più complessi, intacca l’efficienza di macchine che non possono essere usate per nessun altro scopo e che, in media dopo un anno e mezzo circa tenendo conto della legge di Koomey, diventano obsolete, smettono di generare profitto, e devono essere sostituite da nuove ASIC. Una volta che viene sostituita un’asic diventa un RAEE.
            Il grafico presentato mostra una stima delle kilotonnellate di rifiuti elettronici generati dalla sola rete bitcoin. I dati, così come riportati da digiconomist, sono ottenuti facendo una stima lower bound che tiene conto della durata media dell’hardware, del numero di hardware per il mining nella rete, e del peso del suddetto hardware. Così come è possibile ottenere una stima minima di miners presenti nella rete, è possibile anche ottenere il peso minimo dell’hardware utilizzato. I risultati mostrati tengono conto del fatto che l’hardware, vista la legge di Koomey sopra citata, abbia una durata vitale di un anno e mezzo. La stima non tiene conto dell’hardware più pesante e dei sistemi di raffreddamento, ma ci dà un’idea di quanta sia la produzione minima di RAEE dell’intera rete Bitcoin.
            </p>
        </div>
        )   
}

export default ProContro    